# Generated by Django 3.0.1 on 2020-10-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaesy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('guest', 'Visitante')], default='operator', max_length=12, verbose_name='Tipo de Usuário'),
        ),
    ]
