# Generated by Django 3.0.1 on 2020-06-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabb',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterUniqueTogether(
            name='tabb',
            unique_together={('name', 'description')},
        ),
    ]
