"""
Django settings for djaesy project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path

try:
    import gdal
    gdal_path = Path(gdal.__file__)
    OSGEO4W = os.path.join(gdal_path.parent, 'osgeo')
    os.environ["OSGEO4W_ROOT"] = OSGEO4W
    os.environ["GDAL_DATA"] = os.path.join(OSGEO4W, "data", "gdal")
    os.environ["PROJ_LIB"] = os.path.join(OSGEO4W, "data", "proj")
    os.environ["PATH"] = OSGEO4W + ";" + os.environ["PATH"]
    GEOS_LIBRARY_PATH = str(os.path.join(OSGEO4W, "geos_c.dll"))
    GDAL_LIBRARY_PATH = str(os.path.join(OSGEO4W, "gdal301.dll"))
except ImportError:
    GEOS_LIBRARY_PATH = None
    GDAL_LIBRARY_PATH = None

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = 'ff))&l$p9zh!4&lo3_(lc1i(f#k^%!d-hogk$)nf$l%9=fct#q'
DEBUG = True

ROOT_URLCONF = 'sample_project.urls'

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

   # 'channels',

   'django.contrib.admin',
   'django.contrib.auth',
   'django.contrib.contenttypes',
   'django.contrib.sessions',
   'django.contrib.messages',
   'django.contrib.staticfiles',

   # 'django_env_settings',
   #
   # 'django_extensions',

   'rest_framework',
   'rest_framework.authtoken',


    # 'django_cleanup.apps.CleanupConfig',

    'sample_project',

    'djaesy',

    'sandbox'

]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# DJAESY_PERMISSIONS = 'djaesy.permissions'
#
#
# #
# # if DJANGO_SILK and DEBUG:
# #     INSTALLED_APPS += ['silk']
# #     SILKY_PYTHON_PROFILER = True
# #     SILKY_PYTHON_PROFILER_BINARY = True
# #
# AUTH_USER_MODEL = 'djaesy.User'
# # DJAESY_USER_MENU = False

# DJAESY_USER_CREATE_LAYOUT = 'djaesy.'
# DJAESY_USER_UPDATE_LAYOUT = ''
# DJAESY_USER_CREATE_FORM = 'accounts.AccountsUserCreationForm'
# DJAESY_USER_UPDATE_FORM = 'accounts.AccountsUserUpdateForm'
# DJAESY_USER_LIST_VIEW = 'accounts.AccountsUserList'
# DJAESY_USER_UPDATE_VIEW = 'accounts.AccountsUserUpdate'
# DJAESY_USER_CREATE_VIEW = 'accounts.AccountsUserCreate'
# DJAESY_USER_ROLE_CLASS = 'accounts.UserProfile'
#
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#
# if DJANGO_SILK and DEBUG:
#     MIDDLEWARE += ['silk.middleware.SilkyMiddleware']
#
# ROOT_URLCONF = 'sample_project.urls'
#
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#
# WSGI_APPLICATION = 'djaesy.wsgi.application'
# ASGI_APPLICATION = 'djaesy.routing.application'
#
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("redis-server-name", 6379)],
#         },
#     },
# }
#
#
# # Database
# # https://docs.djangoproject.com/en/3.0/ref/settings/#databases
#
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
# #     }
# # }
#
#
# # Password validation
# # https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
# LOGIN_URL = '/login'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'
#
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = ''  # mail service smtp
# EMAIL_HOST_USER = ''  # email id
# EMAIL_HOST_PASSWORD = '' # password
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/3.0/topics/i18n/
#
# LANGUAGE_CODE = 'pt-br'
#
# LOCALE_PATHS = [
#     f'{BASE_DIR}/djaesy/translations',
# ]
#
# LANGUAGES = [
#   ('pt-br', _('Português')),
#   ('en', _('English')),
#   ('zh-cn', _('简体中文')),
# ]
#
# TIME_ZONE = 'America/Sao_Paulo'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/3.0/howto/static-files/
#
STATIC_ROOT = os.path.join(BASE_DIR, '../static/')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, '../media')
MEDIA_URL = '/media/'
#

#
# from easy_thumbnails.conf import Settings as thumbnail_settings
# THUMBNAIL_PROCESSORS = (
#     'image_cropping.thumbnail_processors.crop_corners',
# ) + thumbnail_settings.THUMBNAIL_PROCESSORS
#

#
# # NOMINATIM_URL = 'https://nominatim.openstreetmap.org'
# NOMINATIM_URL = 'http://http://172.20.0.51:7070'
# NOMINATIM_ADDRESS_DISPLAY = [('road', 'village'), ('town', 'county'), 'state', 'country']
#
# APPLICATION_PAGE_TITLE_PREFIX = 'i3Track'
#
#
# # Django Env Settings
# # from django_env_settings import *
